[profile.release]
codegen-units = 1
lto = true

[profile.bench]
inherits = "release"

[workspace]
members = ["hash-bootstrap", "hash-core", "hash-train", "hash-search", "hash-engine"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Yoav Grimland <miestrode@proton.me>"]
edition = "2021"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"