[package]
name = "hash-search"
description = "Chess position search system for game evaluation, part of the Hash Chess Engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hash-core = { path = "../hash-core/" }
rayon = "1.7.0"
portable-atomic = "1.4.2"
